<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table technique des jetons de rafraîchissement JWT, gérée par
 * gesdinet/jwt-refresh-token-bundle (MDD : RefreshToken, « rien à modéliser
 * de notre côté »). Rattachée au compte par username (l'email), sans clé
 * étrangère : le bundle ne connaît pas nos entités.
 */
final class Version20260929203831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Authentification : refresh_tokens (gesdinet/jwt-refresh-token-bundle)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE refresh_tokens');
    }
}
